# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0002_auto_20170412_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizada em'),
        ),
    ]
